### ISSUE TITLE
[mesheryctl] Perf command - panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery#1199]
**Description**
Running `mesheryctl perf` results the following error:

```
$mesheryctl perf --url https://www.google.com
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x16d3c91]

goroutine 1 [running]:
github.com/layer5io/meshery/mesheryctl/internal/cli/root/cfg.(*MesheryCtl).GetBaseMesheryURL(...)
        /Users/runner/runners/2.263.0/work/meshery/meshery/mesheryctl/internal/cli/root/cfg/cfg.go:40
github.com/layer5io/meshery/mesheryctl/internal/cli/root/perf.glob..func2(0x1fa7460, 0xc000434660, 0x0, 0x2, 0x0, 0x0)
        /Users/runner/runners/2.263.0/work/meshery/meshery/mesheryctl/internal/cli/root/perf/perf.go:120 +0x3a1
github.com/spf13/cobra.(*Command).execute(0x1fa7460, 0xc000434640, 0x2, 0x2, 0x1fa7460, 0xc000434640)
        /Users/runner/go/pkg/mod/github.com/spf13/cobra@v0.0.7/command.go:838 +0x460
github.com/spf13/cobra.(*Command).ExecuteC(0x1fa71c0, 0x1a19460, 0x1fd7eb0, 0x0)
        /Users/runner/go/pkg/mod/github.com/spf13/cobra@v0.0.7/command.go:943 +0x317
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/runner/go/pkg/mod/github.com/spf13/cobra@v0.0.7/command.go:883
github.com/layer5io/meshery/mesheryctl/internal/cli/root.Execute()
        /Users/runner/runners/2.263.0/work/meshery/meshery/mesheryctl/internal/cli/root/root.go:87 +0xab
main.main()
        /Users/runner/runners/2.263.0/work/meshery/meshery/mesheryctl/cmd/mesheryctl/main.go:28 +0x93
```

**Environment:**
 - Version: v0.3.17

**Comment by leecalcote** [comment]
@kanishkarj fyi (something for after exams are over)

**Comment by kanishkarj** [comment]
@leecalcote could you try running it on a local build of mesheryctl instead of the release build of mesheryctl. Because it is working on my system. I am assuming it is something with the build.

**Comment by kushthedude** [comment]
> $mesheryctl perf --url https://www.google.com

@leecalcote Can you please verify the issue, as the given argument for the command is invalid?

**Comment by leecalcote** [comment]
This is fine - ![Untitled](https://user-images.githubusercontent.com/7570704/87112561-c5722680-c231-11ea-910c-be00c515fa9f.gif)

**Comment by kushthedude** [comment]
Are we good to close this now?

**Comment by leecalcote** [comment]
This is an attempt with a bad (old) token. Ideally, the error message indicates a bad token, not failed requests.

![Untitled](https://user-images.githubusercontent.com/7570704/87112743-3dd8e780-c232-11ea-8472-3fb86f35c835.gif)

**Comment by leecalcote** [comment]
While we're in here, we may want to update the error message, which currently has "provider=Meshery" as an example token value.

We might also want to put a period on the end of `Error: failed to add auth details to request`, and perhaps, remove the `: file read failed :: open provider=Meshery: no such file or directory` message.

```
➜  ~ mesheryctl perf --url https://www.google.com --token "provider=Meshery"
Error: failed to add auth details to request
See https://meshery.meshery.io/docs/guides/mesheryctl#performance-management for usage details
: file read failed :: open provider=Meshery: no such file or directory
Usage:
  mesheryctl perf [flags]

Examples:
mesheryctl perf --name "a quick stress test" --url http://192.168.1.15/productpage --qps 300 --concurrent-requests 2 --duration 30s --token "provider=Meshery"
```

**Comment by leecalcote** [comment]
Issue has been fixed.
